# -*- coding: utf-8 -*-
"""Accordion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVJpd1LefBWBL5Tga7YJ3BqbpptyY8Ex
"""

import gradio as gr

with gr.Blocks() as demo:
  with gr.Accordion("Basic Accordion"):
    gr.Markdown("This is the content inside the Accordion")

demo.launch()

import gradio as gr

def show_hello():
  return "Hello, World!"

with gr.Blocks() as demo:
  with gr.Accordion(" collapisble section"):
    gr.Markdown("content inside the accordion")

  with gr.Accordion("Another collapsible section", open=True):
    gr.Image("https://cdn.pixabay.com/photo/2024/10/22/07/09/kids-9138810_1280.jpg")

  with gr.Accordion("Yet Another Section"):
    button = gr.Button("Click me")
    button.click(show_hello)

demo.launch()

import gradio as gr

def update_content(expanded):
  return "Expanded Content" if expanded else "Collapsed Content"

with gr.Blocks() as demo:
  with gr.Accordion("Dynamic Content") as accordion:
    dynamic_text = gr.Textbox(label="Content")

  accordion.expand(lambda: update_content(True), outputs=dynamic_text)
  accordion.collapse(lambda: update_content(False), outputs = dynamic_text)

demo.launch()

import gradio as gr
import random
import time

def update_randomly():
  while True:
    yield f"Random: {random.randint(1, 100)}"

with gr.Blocks() as demo:
  with gr.Accordion("Dynamic Updates") as accordion:
    dynamic_output = gr.Textbox(label="Dynamic Text")

  accordion.expand(
      fn=update_randomly,
      outputs=dynamic_output,
      queue=False,
      show_progress=False
  )

  accordion.collapse(
      lambda: "",
      outputs=dynamic_output
  )

demo.launch()

import gradio as gr

def submit_form(name, age):
  return f"Hello, {name}! You are {age} years old."

with gr.Blocks() as demo:
  with gr.Accordion("Content Form"):
    name_input = gr.Textbox(label="Name")
    age_input = gr.Number(label="Age")
    submit_button = gr.Button("Submit")

    submit_button.click(
        fn = submit_form,
        inputs = [name_input, age_input],
        outputs = gr.Textbox(label="Output")
    )

demo.launch()

import gradio as gr

def handle_upload(contents):
  return f"File uploaded successfully!\nSize: {len(contents)} bytes"

with gr.Blocks() as demo:
  with gr.Accordion("File Upload"):
    file_input = gr.File()
    output = gr.Textbox(label="Status")

  file_input.change(
      fn = handle_upload,
      inputs = file_input,
      outputs = output
  )

demo.launch()

import gradio as gr

with gr.Blocks() as demo:
  with gr.Accordion("Code Example", open=False):
      gr.Code('''def Hello():
  print("Hello, World!")''', language="python")

  with gr.Accordion("Another Code Block"):
    gr.Markdown("```javascript\nfunction greeting() {\n  console.log('Hello!');\n}\n```")

demo.launch()

import gradio as gr

with gr.Blocks() as demo:
  with gr.Accordion("Main Section"):
    with gr.Accordion("Subsection 1"):
      gr.Markdown("Content of Subsection 1")

    with gr.Accordion("Subsection 2"):
      gr.Markdown("Content of Subsection 2")

  with gr.Accordion("Another Section"):
    gr.Markdown("Content of Another Section")

demo.launch()

