# -*- coding: utf-8 -*-
"""Group.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_TLXbRCVzjMqJ7ZlV0TCUAs8Ggm8WEY
"""

import gradio as gr

def form_examples(first_name, last_name, email):
  return f"Form submitted successfully! Welcome, {first_name} {last_name}. Your email is {email}."

with gr.Blocks() as demo:
  with gr.Group():
    gr.Markdown("### User Information")
    with gr.Row():
      first_name = gr.Textbox(label="First Name", placeholder="Enter your first name")
      last_name = gr.Textbox(label="Last Name", placeholder="Enter your last name")
    email = gr.Textbox(label="Email", placeholder="Enter your email")
    submit = gr.Button("Submit", variant="primary")
    submit.click(form_examples, inputs=[first_name, last_name, email], outputs=gr.Textbox())

demo.launch()

import gradio as gr

def toolbar_examples(action):
  return f"Action selected: {action}"

with gr.Blocks() as demo:
  with gr.Group():
    gr.Markdown("### Actions")
    with gr.Row():
      cut = gr.Button("Cut", variant="secondary")
      copy = gr.Button("Copy", variant="secondary")
      paste = gr.Button("Paste", variant="secondary")
    cut.click(toolbar_examples, inputs=cut, outputs=gr.Textbox())
    copy.click(toolbar_examples, inputs=copy, outputs=gr.Textbox())
    paste.click(toolbar_examples, inputs=paste, outputs=gr.Textbox())

demo.launch()

import gradio as gr

with gr.Blocks() as demo:
  with gr.Group():
    with gr.Row():
      image = gr.Image(value="image.jpg", label="Photo")
      about = gr.Textbox(label="About", value="This is a brief description of the user.", interactive=False)

demo.launch()

import gradio as gr

def dashboard_examples(update_freq, data_range):
  return f"Dashboard updated with frequenc: {update_freq}, range:{data_range}"

with gr.Blocks() as demo:
  with gr.Group():
    gr.Markdown("### Dashboard Settings")
    with gr.Column():
      update_freq = gr.Dropdown(label="Update Frequency", choices=["Real-time", "5s", "10s", "30s"])
      data_range = gr.Slider(label="Data Range (days)", minimum=1, maximum=30)
      update = gr.Button("Updated Dashboard", variant="primary")
      update.click(dashboard_examples, inputs=[update_freq, data_range], outputs=gr.Textbox())

demo.launch()

import gradio as gr

def create_post(content, tags):
  return f"Post created: {content}\n\n#Tags: {','.join(tags)}"

with gr.Blocks() as demo:
  with gr.Group():
    gr.Markdown("### Create Post")
    content = gr.Textbox(label="Content", placeholder="Write your post here...", lines=4)
    tags = gr.CheckboxGroup(label="Tags", choices=["#Social", "#Life", "#Travel", "#Tech"])
    create = gr.Button("Create Post", variant="primary")
    create.click(create_post, inputs=[content, tags], outputs=gr.Textbox())

demo.launch()

import gradio as gr

def apply_settings(theme, notifications):
  return f"Settings updated: Theme = {theme}, Notifications - {notifications}"

with gr.Blocks() as demo:
  with gr.Group():
    gr.Markdown("### Settings")
    with gr.Row():
      theme = gr.Dropdown(label="Theme", choices=["Light", "Dark", "System"])
      notifications = gr.Checkbox(label="Enable Notifications")
    save = gr.Button("Save Settings", variant="primary")
    save.click(apply_settings, inputs=[theme, notifications], outputs=gr.Textbox())

demo.launch()

import gradio as gr

def compare_products(product1, product2):
  return f"Comparing {product1} and {product2}\n\nAnalysis: [Insert detailed analysis here]"

with gr.Blocks() as demo:
  with gr.Group():
    gr.Markdown("### Product Comparison")
    with gr.Row():
      product1 = gr.Textbox(label="Product 1", placeholder="Enter product name")
      product2 = gr.Textbox(label="Product 2", placeholder="Enter product name")
    compare = gr.Button("Compare", variant="primary")
    compare.click(compare_products, inputs=[product1, product2], outputs=gr.Textbox())

demo.launch()

import gradio as gr

def translate(text, source_lang, target_lang):
  return f"Translation from {source_lang} to {target_lang}:\n{text}"

with gr.Blocks() as demo:
  with gr.Group():
    gr.Markdown("### Translator")
    with gr.Column():
      source_lang = gr.Dropdown(label="Source Language", choices=["English", "Spanish", "French", "German"])
      target_lang = gr.Dropdown(label="Target Language", choices=["English", "Spanish", "French", "German"])
      text = gr.Textbox(label="Enter Text", placeholder="Type here...", lines=3)
      translate_button = gr.Button("Translate", variant="primary")
      output = gr.Textbox(label="Translation", interactive=False)
      translate_button.click(translate, inputs=[text, source_lang, target_lang], outputs=output)

demo.launch()

