# -*- coding: utf-8 -*-
"""Tab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oPwAcuKEalTroVpIM0IFFmArXpp-Mp6f
"""

import gradio as gr

with gr.Blocks() as demo:
  with gr.Tab("Tab 1"):
    gr.Textbox(label="This is Tab 1", value="Content for Tab 1")
  with gr.Tab("Tab 2"):
    gr.Textbox(label="This is Tab 2", value="Content for Tab 2")
  with gr.Tab("Tab 3"):
    gr.Textbox(label="This is Tab 3", value="Content for Tab 3")

demo.launch()

import gradio as gr

with gr.Blocks() as demo:
  with gr.Tab("🏠 Home"):
    gr.Textbox(label="Home Tab", value="Welcome to the Home Tab!")
  with gr.Tab("⚙️ Settings"):
    gr.Textbox(label="Settings Tab", value="Adjust your settings here.")
  with gr.Tab("❓ Help"):
    gr.Textbox(label="Help Tab", value="Get help here")

demo.launch()

import gradio as gr

def greet(name):
  return f"Hello, {name}!"

with gr.Blocks() as demo:
  with gr.Tab("Greetings"):
    name = gr.Textbox(label="Enter your name")
    button = gr.Button("Greet Me")
    output = gr.Textbox(label="Greeting")
    button.click(greet, inputs=name, outputs=output)
  with gr.Tab("About"):
    gr.Textbox(label="About Us", value="This is an example application")

demo.launch()

import gradio as gr

def calculate_sum(num1, num2):
  return f"Sum: {num1+num2}"

with gr.Blocks() as demo:
  with gr.Tab("Tab 1"):
    num1 = gr.Number(label="Number 1")
    num2 = gr.Number(label="Number 2")
    button = gr.Button("Calculate Sum")
    output = gr.Textbox(label="Result")
    button.click(calculate_sum, inputs=[num1, num2], outputs=output)
  with gr.Tab("Tab 2"):
    gr.Textbox(label="Enter text here", value="Type something...")

demo.launch()

import gradio as gr

with gr.Blocks() as demo:
  with gr.Tab("Small Tab", scale=1):
    gr.Textbox(label="This tab has scale=1")
  with gr.Tab("Medium Tab", scale=2):
    gr.Textbox(label="This tab has scale=2")
  with gr.Tab("Large Tab", scale=3):
    gr.Textbox(label="This tab has scale=3")

demo.launch()

import gradio as gr

with gr.Blocks() as demo:
  with gr.Tab("Visible Tab", visible=True):
    gr.Textbox(label="This tab is visible by default")
  with gr.Tab("Invisible Tab", visible=True):
    gr.Textbox(label="This tab is invisible by default")

demo.launch()

import gradio as gr

def toggle_visibility(visible):
  return visible

with gr.Blocks() as demo:
  with gr.Tab("Show Components") as tab1:
    show = gr.Checkbox(label="Show Component", value=False)
  with gr.Tab("Component") as tab2:
    component = gr.Textbox(label="This component's visibility depends on the checkbox", visible=False)

  show.change(toggle_visibility, inputs=show, outputs=component)

demo.launch()

import gradio as gr

with gr.Blocks() as demo:
  with gr.Tab("Styled Tab", elem_id="custom-tab", elem_classes=["tab-class"]):
    gr.Textbox(label="Custom Styled Textbox", elem_id="custom_textbox")

  with gr.Tab("Default Tab"):
    gr.Textbox(label="Default Textbox")

demo.launch()

import gradio as gr


with gr.Blocks() as demo:
  with gr.Tab("input Tab"):
    name = gr.Textbox(label="Enter your name")
    age = gr.Number(label="Enter your age")
    button = gr.Button("Submit")
  with gr.Tab("Output Tab"):
    output = gr.Textbox(label="Output", visible=False)

  button.click(
      lambda name, age: f"Name: {name}, Age: {age}",
      inputs= [name, age],
      outputs= output
  )

demo.launch()

