# -*- coding: utf-8 -*-
"""Intro to ChatInterface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FnE-nBQ77_vaulieeECU0pifo6240-M1
"""

pip install gradio

import gradio as gr
import random

def random_response(message, history):
  return random.choice(["Yes", "No"])

demo = gr.ChatInterface(random_response, type="messages", title="Random Answer Bot")
demo.launch()

import gradio as gr

def calculator(message, history):
  try:
    result = eval(message)
    return f"Result: {result}"
  except:
    return "Invalid expression. Use numbers and operators only"

demo = gr.ChatInterface(calculator, type="messages", title="Calculator Bot")
demo.launch()

import gradio as gr
import random

jokes = [
    "Why don't eggs fight? They would eff each other on!",
    "What do you call a bear with no ears? B-!"
]

def tell_joke(message, history):
  return random.choice(jokes)

demo = gr.ChatInterface(tell_joke, type="messages", title="Joke Bot")
demo.launch()

import gradio as gr


def word_counter(message, history):
  return f"Your message contains {len(message.split())} words."

demo = gr.ChatInterface(word_counter, title="Word Counter Bot")
demo.launch()

import gradio as gr

weather_data = {
    "London": "Cloudy, 12C",
    "Delhi": "Sunny 22C",
    "Mumbai": "Rainy 11C"
}

def weather_bot(message, history):
  city = message.capitalize()
  return weather_data.get(city, "City not found.")

demo = gr.ChatInterface(weather_bot, title="Weather Bot")
demo.launch()

import gradio as gr

def color_picker(message, history):
  colors = ["red", "blue", "green", "yellow", "pink"]
  return f"Here are some colors: {random.sample(colors, 3)}"

demo = gr.ChatInterface(color_picker, title="Color Picker")
demo.launch()

import gradio as gr

definitions = {
    "hello": "A greeting",
    "goodbye": "A farewell"
}

def dictionary_bot(message, history):
  return definitions.get(message, "Word not found")

demo = gr.ChatInterface(dictionary_bot, title="Dictionary Bot")
demo.launch()

import gradio as gr
import random

facts = [
    "Honey never spoils.",
    "The shortest war lasted 38 minutes",
    "I am the best mentor you guys have..."
]

def random_fact(message, history):
  return random.choice(facts)

demo = gr.ChatInterface(random_fact, type="messages", title="Random Fact Bot")
demo.launch()

import gradio as gr
import random

quotes = [
    "Be the change you wish to see in the world.",
    "In three words I cam sum everything I've learned about life: it goes on."
]

def random_quote(message, history):
  return random.choice(quotes)

demo = gr.ChatInterface(random_quote, title="Quote Bot")
demo.launch()

import gradio as gr

def poll_bot(message, history):
  if not history:
    return "Do you prefer coffee or tea?"
  preferences = ["Coffee", "Tea"]
  return f"You prefer {message}"

demo = gr.ChatInterface(poll_bot, title="Poll Bot")
demo.launch()

import gradio as gr

def reverse_sentence(message, history):
  return " ".join(reversed(message.split()))

demo = gr.ChatInterface(reverse_sentence, title="Sentence Reversal Bot")
demo.launch()

